"""Utility script to build a 100-question accounting dataset."""
from __future__ import annotations

import json

import pandas as pd


def q(
    module: str,
    question: str,
    options: list[str],
    answer: str,
    difficulty: str,
    explanation: str,
    *,
    correct_answers: list[str] | None = None,
    allow_multiple: bool | None = None,
) -> dict:
    answers = correct_answers or [answer]
    allow_multi = allow_multiple if allow_multiple is not None else len(answers) > 1
    return {
        "module": module,
        "question": question,
        "options": options,
        "answer": answers[0],
        "correct_answers": answers,
        "allow_multiple": allow_multi,
        "difficulty": difficulty,
        "image": "",
        "explanation": explanation,
    }


questions: list[dict] = []

# Budgeting (10) – real-life multi-select examples
questions += [
    q(
        "Budgeting",
        "Which of the following are objectives of budgets? (Select all that apply)",
        ["Motivation", "Strategy", "Communication", "Responsibility"],
        "Motivation",
        "Medium",
        "Budgets motivate teams, translate strategy into action, communicate expectations, and allocate responsibility for delivery.",
        correct_answers=["Motivation", "Strategy", "Communication", "Responsibility"],
        allow_multiple=True,
    ),
    q(
        "Budgeting",
        "Which statements describe an objective of budgeting? (Select all that apply)",
        [
            "Translating strategic goals into plans to enable an entity to achieve its objectives.",
            "Forcing entities to look ahead and plan for the future.",
            "Forcing entities to report on the financial outcomes of the past 12 months.",
            "Coordinating the different functions of an entity.",
        ],
        "Translating strategic goals into plans to enable an entity to achieve its objectives.",
        "Medium",
        "Budgets convert strategy into concrete plans, force forward-looking thinking, and coordinate functions—unlike backward-looking financial reporting.",
        correct_answers=[
            "Translating strategic goals into plans to enable an entity to achieve its objectives.",
            "Forcing entities to look ahead and plan for the future.",
            "Coordinating the different functions of an entity.",
        ],
        allow_multiple=True,
    ),
    q(
        "Budgeting",
        "Which statements describe the motivational objective of budgeting? (Select all that apply)",
        [
            "Delegating responsibility for different parts of the budget.",
            "Employees work more effectively if they have a challenging target to aim for.",
            "Setting targets against which actual results will be compared.",
            "Incentivizing staff to work towards achieving a budgeted target.",
        ],
        "Employees work more effectively if they have a challenging target to aim for.",
        "Medium",
        "Budgets motivate by giving people stretching targets and linking incentives to hitting those targets.",
        correct_answers=[
            "Employees work more effectively if they have a challenging target to aim for.",
            "Incentivizing staff to work towards achieving a budgeted target.",
        ],
        allow_multiple=True,
    ),
    q(
        "Budgeting",
        "Breaking down one big task into smaller tasks helps allocate responsibility for achieving organizational objectives.",
        ["True", "False"],
        "True",
        "Easy",
        "Disaggregating a master target clarifies who owns each portion of the plan, improving accountability.",
    ),
    q(
        "Budgeting",
        "What is the first step in the budgeting process?",
        [
            "Decide on the selling prices for products.",
            "Calculate the variable costs for products.",
            "Talk to suppliers about price movements over the coming year.",
            "Decide on the strategy and objectives of the organization.",
        ],
        "Decide on the strategy and objectives of the organization.",
        "Easy",
        "Budgeting starts with strategic intent—without agreed goals, numeric targets lack direction.",
    ),
    q(
        "Budgeting",
        "Which budget should entities prepare first?",
        ["Cash budget", "Budgeted statement of profit or loss", "Variable costs budget", "Sales budget"],
        "Sales budget",
        "Easy",
        "Sales expectations drive production, staffing, and cash forecasts, so the sales budget anchors the remaining schedules.",
    ),
    q(
        "Budgeting",
        "The budgeted monthly statement of profit or loss is drawn up on a cash basis while the cash budget is prepared on the accruals basis.",
        ["True", "False"],
        "False",
        "Medium",
        "It is the income statement that follows accrual principles, whereas the cash budget focuses purely on cash receipts and payments.",
    ),
    q(
        "Budgeting",
        "Which control activities are typically undertaken each month? (Select all that apply)",
        [
            "Sensitivity analysis of budgets.",
            "Comparing actual and budgeted results.",
            "Identifying variances in cash receipts and payments.",
            "Taking corrective action on negative variances.",
        ],
        "Comparing actual and budgeted results.",
        "Medium",
        "Monthly control loops compare actuals to budget, flag cash variances, and trigger corrective action; sensitivity work is usually periodic.",
        correct_answers=[
            "Comparing actual and budgeted results.",
            "Identifying variances in cash receipts and payments.",
            "Taking corrective action on negative variances.",
        ],
        allow_multiple=True,
    ),
    q(
        "Budgeting",
        "Monthly comparisons of actual results versus budgeted results are examples of relevant financial information.",
        ["True", "False"],
        "True",
        "Easy",
        "Variance reports are timely, decision-focused insights that help managers steer performance, so they are highly relevant.",
    ),
    q(
        "Budgeting",
        "Sensitivity analysis assesses the effect on profits and cash flows of actual outcomes in comparison to budgeted outcomes.",
        ["True", "False"],
        "False",
        "Medium",
        "Sensitivity analysis tests how changing key assumptions (not actual results) would impact profits and cash, providing a what-if view.",
    ),
]

# Accounting Basics (15)
questions += [
    q(
        "Accounting Basics",
        "Which statement best describes double-entry bookkeeping?",
        [
            "Each transaction affects at least two accounts with equal debits and credits",
            "Every entry is recorded twice at different times",
            "Debits must always exceed credits",
            "Transactions are recorded only at period end",
        ],
        "Each transaction affects at least two accounts with equal debits and credits",
        "Easy",
        "Double-entry accounting records dual effects so total debits always equal total credits.",
    ),
    q(
        "Accounting Basics",
        "Which type of account normally increases with a debit?",
        ["Cash", "Service Revenue", "Accounts Payable", "Retained Earnings"],
        "Cash",
        "Easy",
        "Asset accounts such as Cash increase with debits and decrease with credits.",
    ),
    q(
        "Accounting Basics",
        "GAAP is an acronym for which phrase?",
        [
            "Generally Accepted Accounting Principles",
            "Global Association of Auditing Professionals",
            "Government Authorized Accounting Policies",
            "General Appraisal and Assessment Procedures",
        ],
        "Generally Accepted Accounting Principles",
        "Easy",
        "GAAP stands for Generally Accepted Accounting Principles, the U.S. reporting framework.",
    ),
    q(
        "Accounting Basics",
        "Which of the following is classified as a current asset?",
        ["Inventory", "Bonds Payable", "Common Stock", "Accumulated Depreciation"],
        "Inventory",
        "Easy",
        "Inventory is expected to be sold or converted to cash within one year, so it is a current asset.",
    ),
    q(
        "Accounting Basics",
        "Which principle requires expenses to be recorded in the same period as the revenues they help generate?",
        ["Matching principle", "Conservatism", "Objectivity", "Materiality"],
        "Matching principle",
        "Medium",
        "The matching principle aligns expenses with the revenues they support to report proper profit.",
    ),
    q(
        "Accounting Basics",
        "Which form of organization most commonly provides limited liability to its owners?",
        ["Corporation", "General partnership", "Sole proprietorship", "Joint venture"],
        "Corporation",
        "Easy",
        "Corporate shareholders are typically liable only up to their investment, unlike sole proprietors or partners.",
    ),
    q(
        "Accounting Basics",
        "Which assumption treats a business as separate from its owners for accounting purposes?",
        [
            "Economic entity assumption",
            "Going concern assumption",
            "Monetary unit assumption",
            "Periodicity assumption",
        ],
        "Economic entity assumption",
        "Medium",
        "The economic entity assumption states personal and business transactions must be kept separate.",
    ),
    q(
        "Accounting Basics",
        "Recording assets at the price paid to acquire them follows which concept?",
        [
            "Historical cost principle",
            "Revenue recognition principle",
            "Fair value option",
            "Consistency principle",
        ],
        "Historical cost principle",
        "Medium",
        "Historical cost requires assets to be recorded at their original purchase price and not market value.",
    ),
    q(
        "Accounting Basics",
        "Accrual basis accounting recognizes revenue when it is",
        [
            "Earned, regardless of when cash is received",
            "Collected in cash only",
            "Deposited by customers",
            "Approved by the tax authority",
        ],
        "Earned, regardless of when cash is received",
        "Easy",
        "Accrual accounting records revenue when the earning process is complete even if payment is deferred.",
    ),
    q(
        "Accounting Basics",
        "The primary purpose of a trial balance is to",
        [
            "Verify that total debits equal total credits",
            "Prepare tax returns",
            "Detect every possible accounting error",
            "Provide cash flow information",
        ],
        "Verify that total debits equal total credits",
        "Easy",
        "A trial balance lists debits and credits to confirm the ledger is in balance before adjustments.",
    ),
    q(
        "Accounting Basics",
        "Which account typically carries a credit balance?",
        ["Unearned revenue", "Prepaid insurance", "Equipment", "Supplies"],
        "Unearned revenue",
        "Easy",
        "Unearned revenue is a liability and liabilities normally carry credit balances.",
    ),
    q(
        "Accounting Basics",
        "Which step usually comes first in the accounting cycle?",
        [
            "Analyze and record transactions",
            "Prepare adjusting entries",
            "Compile the post-closing trial balance",
            "Prepare financial statements",
        ],
        "Analyze and record transactions",
        "Easy",
        "The accounting cycle begins by analyzing source documents and recording journal entries.",
    ),
    q(
        "Accounting Basics",
        "An owner invests additional cash into the business. Which accounts are affected?",
        [
            "Cash increases and owner's capital increases",
            "Cash decreases and owner's capital increases",
            "Cash increases and expenses increase",
            "Cash decreases and liabilities decrease",
        ],
        "Cash increases and owner's capital increases",
        "Easy",
        "Owner investments raise both the Cash asset and the Owner's Capital equity account.",
    ),
    q(
        "Accounting Basics",
        "Providing services on account results in",
        [
            "Increasing Accounts Receivable and Service Revenue",
            "Increasing Cash and Unearned Revenue",
            "Decreasing Accounts Receivable and increasing Cash",
            "Increasing Expenses and Liabilities",
        ],
        "Increasing Accounts Receivable and Service Revenue",
        "Easy",
        "Revenue earned on account raises receivables and revenue even though no cash is collected yet.",
    ),
    q(
        "Accounting Basics",
        "Which error would not be detected by a trial balance?",
        [
            "Omitting an entire transaction",
            "Recording equal debits and credits in wrong accounts",
            "Posting a debit as a credit of different amount",
            "Transposing digits on only one side",
        ],
        "Omitting an entire transaction",
        "Medium",
        "If a transaction is never recorded, both debit and credit totals remain equal so the trial balance still balances.",
    ),
]

# Financial Statements (20)
questions += [
    q(
        "Financial Statements",
        "Which financial statement is prepared at a specific point in time rather than for a period?",
        ["Balance sheet", "Income statement", "Statement of cash flows", "Statement of retained earnings"],
        "Balance sheet",
        "Easy",
        "The balance sheet presents assets, liabilities, and equity as of a particular date.",
    ),
    q(
        "Financial Statements",
        "Which statement reconciles the beginning and ending balances of retained earnings?",
        [
            "Statement of retained earnings",
            "Statement of cash flows",
            "Income statement",
            "Balance sheet",
        ],
        "Statement of retained earnings",
        "Easy",
        "The retained earnings statement adds net income and subtracts dividends to show the ending balance.",
    ),
    q(
        "Financial Statements",
        "What is the primary purpose of the statement of cash flows?",
        [
            "Explain the change in cash between two balance sheet dates",
            "Calculate taxable income",
            "Summarize non-cash expenses",
            "Reconcile retained earnings",
        ],
        "Explain the change in cash between two balance sheet dates",
        "Easy",
        "The cash flow statement details operating, investing, and financing movements that reconcile beginning and ending cash.",
    ),
    q(
        "Financial Statements",
        "Which of the following is an investing activity on the statement of cash flows?",
        [
            "Purchasing new equipment for cash",
            "Paying quarterly dividends",
            "Collecting receivables",
            "Issuing common stock",
        ],
        "Purchasing new equipment for cash",
        "Medium",
        "Buying or selling long-term assets is reported in the investing section.",
    ),
    q(
        "Financial Statements",
        "Where is accumulated depreciation reported?",
        [
            "As a contra-asset in the property, plant, and equipment section",
            "Within current liabilities",
            "On the income statement as other expense",
            "Only in the notes to the financial statements",
        ],
        "As a contra-asset in the property, plant, and equipment section",
        "Medium",
        "Accumulated depreciation reduces the carrying amount of property, plant, and equipment on the balance sheet.",
    ),
    q(
        "Financial Statements",
        "Which ordering of major asset sections is standard on a classified balance sheet?",
        [
            "Current assets, long-term investments, property plant and equipment, intangible assets",
            "Long-term investments, current assets, intangible assets, property plant and equipment",
            "Intangible assets, current assets, PPE, long-term investments",
            "Property plant and equipment, current assets, intangible assets, long-term investments",
        ],
        "Current assets, long-term investments, property plant and equipment, intangible assets",
        "Medium",
        "Classified balance sheets present assets from most liquid (current) to least liquid (intangibles).",
    ),
    q(
        "Financial Statements",
        "Which item is reported in other comprehensive income rather than net income?",
        [
            "Unrealized gain on available-for-sale debt securities",
            "Realized gain from selling equipment",
            "Cash paid for inventory",
            "Interest expense on bonds",
        ],
        "Unrealized gain on available-for-sale debt securities",
        "Hard",
        "Certain unrealized gains and losses bypass net income and flow through other comprehensive income until realized.",
    ),
    q(
        "Financial Statements",
        "Which statement reports the total of other comprehensive income?",
        [
            "Statement of comprehensive income",
            "Statement of cash flows",
            "Balance sheet",
            "Notes to the financial statements",
        ],
        "Statement of comprehensive income",
        "Medium",
        "Comprehensive income statements extend the income statement to add other comprehensive income items.",
    ),
    q(
        "Financial Statements",
        "A multi-step income statement uniquely highlights which subtotal?",
        ["Gross profit", "Ending cash", "Comprehensive income", "Total assets"],
        "Gross profit",
        "Medium",
        "The multi-step format shows gross profit and operating income before other revenues and expenses.",
    ),
    q(
        "Financial Statements",
        "Under U.S. GAAP, cash paid for interest is reported in which section of the statement of cash flows?",
        ["Operating activities", "Investing activities", "Financing activities", "Supplemental schedule only"],
        "Operating activities",
        "Medium",
        "GAAP classifies cash interest paid as an operating outflow even though it relates to financing.",
    ),
    q(
        "Financial Statements",
        "Which of the following transactions is reported as a financing cash flow?",
        [
            "Issuing new shares of common stock",
            "Paying wages",
            "Purchasing office supplies",
            "Collecting interest income",
        ],
        "Issuing new shares of common stock",
        "Medium",
        "Financing activities include obtaining capital from owners or lenders and returning capital via dividends or debt repayment.",
    ),
    q(
        "Financial Statements",
        "Which event reduces retained earnings but does not appear on the income statement?",
        [
            "Declaring a cash dividend",
            "Recording depreciation expense",
            "Recognizing cost of goods sold",
            "Paying utility expense",
        ],
        "Declaring a cash dividend",
        "Medium",
        "Dividends reduce retained earnings directly and are distributions, not expenses.",
    ),
    q(
        "Financial Statements",
        "The book value of property, plant, and equipment equals",
        [
            "Historical cost minus accumulated depreciation",
            "Replacement cost minus salvage value",
            "Fair value minus book value",
            "Original cost plus accumulated depreciation",
        ],
        "Historical cost minus accumulated depreciation",
        "Easy",
        "Carrying amount for depreciable assets equals their recorded cost less accumulated depreciation.",
    ),
    q(
        "Financial Statements",
        "Where is treasury stock reported?",
        [
            "As a contra-equity account in stockholders' equity",
            "As a current asset",
            "Within other comprehensive income",
            "As a long-term investment",
        ],
        "As a contra-equity account in stockholders' equity",
        "Medium",
        "Treasury stock reduces total equity because it represents shares repurchased by the issuer.",
    ),
    q(
        "Financial Statements",
        "Which statement reports 'Net cash used by investing activities'?",
        ["Statement of cash flows", "Income statement", "Statement of retained earnings", "Balance sheet"],
        "Statement of cash flows",
        "Easy",
        "The cash flow statement details operating, investing, and financing cash totals for the period.",
    ),
    q(
        "Financial Statements",
        "Where would 'Notes Receivable due in 18 months' be classified?",
        ["Noncurrent assets", "Current assets", "Other comprehensive income", "Current liabilities"],
        "Noncurrent assets",
        "Medium",
        "Receivables collectible beyond one year are classified as long-term or noncurrent assets.",
    ),
    q(
        "Financial Statements",
        "Which statement explains the change in each equity account, including common stock and retained earnings?",
        [
            "Statement of stockholders' equity",
            "Statement of cash flows",
            "Income statement",
            "Notes to the financial statements",
        ],
        "Statement of stockholders' equity",
        "Medium",
        "The equity statement reconciles beginning and ending balances for each equity component.",
    ),
    q(
        "Financial Statements",
        "Which balance sheet figure must equal the ending cash shown on the statement of cash flows?",
        ["Cash and cash equivalents", "Total assets", "Working capital", "Net income"],
        "Cash and cash equivalents",
        "Easy",
        "The cash flow statement reconciles to the balance sheet line 'Cash and cash equivalents' at period end.",
    ),
    q(
        "Financial Statements",
        "Where would 'Bonds payable due in five years' appear?",
        ["Noncurrent liabilities", "Current liabilities", "Current assets", "Other comprehensive income"],
        "Noncurrent liabilities",
        "Easy",
        "Obligations due beyond one year are classified as long-term or noncurrent liabilities.",
    ),
    q(
        "Financial Statements",
        "Which classification describes 'Allowance for Doubtful Accounts' on the balance sheet?",
        ["Contra-asset", "Asset", "Liability", "Equity"],
        "Contra-asset",
        "Medium",
        "The allowance offsets Accounts Receivable and reduces the asset to its net realizable value.",
    ),
]

# Journal Entries & Adjustments (15)
questions += [
    q(
        "Journal Entries & Adjustments",
        "What is the adjusting entry when previously unearned revenue is now earned?",
        [
            "Debit Unearned Revenue; credit Service Revenue",
            "Debit Service Revenue; credit Cash",
            "Debit Accounts Receivable; credit Service Revenue",
            "Debit Cash; credit Unearned Revenue",
        ],
        "Debit Unearned Revenue; credit Service Revenue",
        "Medium",
        "Earning the revenue reduces the liability and increases revenue.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Which entry records monthly depreciation on equipment?",
        [
            "Debit Depreciation Expense; credit Accumulated Depreciation",
            "Debit Equipment; credit Depreciation Expense",
            "Debit Accumulated Depreciation; credit Cash",
            "Debit Repairs Expense; credit Equipment",
        ],
        "Debit Depreciation Expense; credit Accumulated Depreciation",
        "Easy",
        "Depreciation expense recognizes cost allocation, while the contra-asset accumulates the credited amount.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Which entry records accrued salaries owed to employees?",
        [
            "Debit Salaries Expense; credit Salaries Payable",
            "Debit Salaries Payable; credit Salaries Expense",
            "Debit Cash; credit Salaries Expense",
            "Debit Salaries Expense; credit Accounts Receivable",
        ],
        "Debit Salaries Expense; credit Salaries Payable",
        "Easy",
        "At period end, the company recognizes the expense and a liability for unpaid wages.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Under the allowance method, writing off a specific uncollectible account requires",
        [
            "Debiting Allowance for Doubtful Accounts and crediting Accounts Receivable",
            "Debiting Bad Debt Expense and crediting Cash",
            "Debiting Accounts Receivable and crediting Allowance",
            "Debiting Retained Earnings and crediting Accounts Receivable",
        ],
        "Debiting Allowance for Doubtful Accounts and crediting Accounts Receivable",
        "Medium",
        "Write-offs use the existing allowance balance and remove the specific receivable without affecting expense.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Accumulated Depreciation is classified as which type of account?",
        ["Contra-asset", "Revenue", "Expense", "Current liability"],
        "Contra-asset",
        "Easy",
        "Accumulated Depreciation offsets the related asset account and carries a credit balance.",
    ),
    q(
        "Journal Entries & Adjustments",
        "What is the primary purpose of closing entries?",
        [
            "Transfer temporary account balances to retained earnings",
            "Update asset accounts to fair value",
            "Record cash receipts and disbursements",
            "Prepare bank reconciliations",
        ],
        "Transfer temporary account balances to retained earnings",
        "Medium",
        "Closing entries zero out revenues, expenses, and dividends to update retained earnings for the new period.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Which of the following is a temporary (nominal) account?",
        ["Service Revenue", "Accumulated Depreciation", "Notes Payable", "Common Stock"],
        "Service Revenue",
        "Easy",
        "Revenues and expenses are temporary accounts closed each period, unlike balance sheet accounts.",
    ),
    q(
        "Journal Entries & Adjustments",
        "What is the journal entry when supplies are purchased on account?",
        [
            "Debit Supplies; credit Accounts Payable",
            "Debit Accounts Payable; credit Supplies",
            "Debit Supplies Expense; credit Cash",
            "Debit Cash; credit Supplies",
        ],
        "Debit Supplies; credit Accounts Payable",
        "Easy",
        "Buying supplies on account increases the Supplies asset and creates a liability to the vendor.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Paying a previously recorded accounts payable requires which entry?",
        [
            "Debit Accounts Payable; credit Cash",
            "Debit Cash; credit Accounts Payable",
            "Debit Accounts Payable; credit Supplies",
            "Debit Expense; credit Cash",
        ],
        "Debit Accounts Payable; credit Cash",
        "Easy",
        "Settling the liability removes Accounts Payable and reduces Cash.",
    ),
    q(
        "Journal Entries & Adjustments",
        "What is the adjusting entry to recognize accrued interest revenue?",
        [
            "Debit Interest Receivable; credit Interest Revenue",
            "Debit Interest Expense; credit Interest Payable",
            "Debit Cash; credit Interest Revenue",
            "Debit Interest Revenue; credit Unearned Revenue",
        ],
        "Debit Interest Receivable; credit Interest Revenue",
        "Medium",
        "If interest has been earned but not collected, receivable and revenue must be recorded.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Receiving cash before earning revenue initially results in",
        [
            "Increasing Cash and Unearned Revenue",
            "Increasing Cash and Service Revenue",
            "Increasing Accounts Receivable and Revenue",
            "Increasing Revenue and Expenses",
        ],
        "Increasing Cash and Unearned Revenue",
        "Easy",
        "Cash in advance creates a liability until the company performs the service or delivers goods.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Which entry records the periodic bad debt estimate under the allowance method?",
        [
            "Debit Bad Debt Expense; credit Allowance for Doubtful Accounts",
            "Debit Allowance for Doubtful Accounts; credit Accounts Receivable",
            "Debit Accounts Receivable; credit Bad Debt Expense",
            "Debit Sales Returns; credit Allowance",
        ],
        "Debit Bad Debt Expense; credit Allowance for Doubtful Accounts",
        "Medium",
        "The adjusting entry recognizes anticipated credit losses through expense and the contra-asset allowance.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Posting in the accounting cycle refers to",
        [
            "Transferring journal entries to the general ledger",
            "Recording transactions in the journal",
            "Preparing the bank reconciliation",
            "Closing the books",
        ],
        "Transferring journal entries to the general ledger",
        "Easy",
        "Posting updates each ledger account with the amounts recorded in the journal.",
    ),
    q(
        "Journal Entries & Adjustments",
        "Why do some companies use reversing entries?",
        [
            "To simplify recording of routine accruals in the next period",
            "To eliminate the need for closing entries",
            "To convert accrual accounting to cash basis",
            "To avoid preparing financial statements",
        ],
        "To simplify recording of routine accruals in the next period",
        "Medium",
        "Reversing certain adjusting entries allows the next period's cash payment or receipt to be recorded normally without duplication.",
    ),
    q(
        "Journal Entries & Adjustments",
        "What entry is required when a company pays a previously declared cash dividend?",
        [
            "Debit Dividends Payable; credit Cash",
            "Debit Dividends; credit Cash",
            "Debit Cash; credit Dividends Payable",
            "Debit Retained Earnings; credit Cash",
        ],
        "Debit Dividends Payable; credit Cash",
        "Easy",
        "At payment, the liability is removed and cash decreases; retained earnings were reduced when the dividend was declared.",
    ),
]

# Financial Ratios (20)
questions += [
    q(
        "Financial Ratios",
        "What is the formula for the current ratio?",
        [
            "Current assets divided by current liabilities",
            "Total assets divided by total liabilities",
            "Current assets minus current liabilities",
            "Current liabilities divided by total equity",
        ],
        "Current assets divided by current liabilities",
        "Easy",
        "The current ratio evaluates liquidity by comparing short-term resources to obligations due within a year.",
    ),
    q(
        "Financial Ratios",
        "Which expression represents the quick (acid-test) ratio?",
        [
            "(Current assets - inventory - prepaid expenses) / current liabilities",
            "Current assets / total assets",
            "Current assets + inventory / current liabilities",
            "Cash / total liabilities",
        ],
        "(Current assets - inventory - prepaid expenses) / current liabilities",
        "Medium",
        "The quick ratio removes less liquid items such as inventory and prepaids from the numerator.",
    ),
    q(
        "Financial Ratios",
        "Working capital is calculated by",
        [
            "Subtracting current liabilities from current assets",
            "Dividing total liabilities by total equity",
            "Subtracting total expenses from total revenues",
            "Adding cash to retained earnings",
        ],
        "Subtracting current liabilities from current assets",
        "Easy",
        "Working capital measures the cushion of short-term assets over short-term obligations.",
    ),
    q(
        "Financial Ratios",
        "Gross profit margin equals",
        [
            "Gross profit divided by net sales",
            "Net income divided by total assets",
            "Gross profit divided by total assets",
            "Net sales divided by gross profit",
        ],
        "Gross profit divided by net sales",
        "Easy",
        "Gross margin expresses gross profit as a percentage of net sales revenue.",
    ),
    q(
        "Financial Ratios",
        "Operating margin is calculated as",
        [
            "Operating income divided by net sales",
            "Operating expenses divided by net sales",
            "Net income divided by operating income",
            "Operating income divided by total assets",
        ],
        "Operating income divided by net sales",
        "Medium",
        "Operating margin reflects the proportion of sales left after covering operating costs.",
    ),
    q(
        "Financial Ratios",
        "Net profit margin uses which formula?",
        [
            "Net income divided by net sales",
            "Net income divided by average equity",
            "Net income divided by total assets",
            "Net sales divided by average assets",
        ],
        "Net income divided by net sales",
        "Easy",
        "Net profit margin measures the percentage of each sales dollar that becomes profit.",
    ),
    q(
        "Financial Ratios",
        "Return on assets (ROA) is computed as",
        [
            "Net income divided by average total assets",
            "Net income divided by average equity",
            "Operating income divided by current assets",
            "Net sales divided by average assets",
        ],
        "Net income divided by average total assets",
        "Medium",
        "ROA gauges how effectively assets generate profit using average assets in the denominator.",
    ),
    q(
        "Financial Ratios",
        "Return on equity (ROE) equals",
        [
            "(Net income - preferred dividends) / average common equity",
            "Net income / average total assets",
            "Net income / net sales",
            "Gross profit / average equity",
        ],
        "(Net income - preferred dividends) / average common equity",
        "Medium",
        "ROE measures profitability attributable to common shareholders after preferred dividends.",
    ),
    q(
        "Financial Ratios",
        "Asset turnover is calculated by",
        [
            "Net sales divided by average total assets",
            "Average total assets divided by net sales",
            "Net income divided by total assets",
            "Gross profit divided by total assets",
        ],
        "Net sales divided by average total assets",
        "Medium",
        "Asset turnover shows how efficiently assets generate sales revenue.",
    ),
    q(
        "Financial Ratios",
        "Inventory turnover uses which formula?",
        [
            "Cost of goods sold divided by average inventory",
            "Average inventory divided by cost of goods sold",
            "Net sales divided by ending inventory",
            "Ending inventory divided by cost of goods sold",
        ],
        "Cost of goods sold divided by average inventory",
        "Medium",
        "Inventory turnover measures how many times inventory is sold during the period.",
    ),
    q(
        "Financial Ratios",
        "Days sales outstanding (DSO) is approximated by",
        [
            "(Accounts receivable / net credit sales) × 365",
            "Net credit sales / accounts receivable",
            "Accounts receivable / cost of goods sold",
            "Net income / accounts receivable",
        ],
        "(Accounts receivable / net credit sales) × 365",
        "Hard",
        "DSO converts receivable turnover to days by multiplying the reciprocal by 365.",
    ),
    q(
        "Financial Ratios",
        "Times interest earned measures",
        [
            "The ability to cover interest using earnings before interest and taxes",
            "The number of years until bonds mature",
            "How quickly interest is paid in cash",
            "The rate earned on interest-bearing accounts",
        ],
        "The ability to cover interest using earnings before interest and taxes",
        "Medium",
        "TIE = EBIT / interest expense and indicates how comfortably a firm can pay interest charges.",
    ),
    q(
        "Financial Ratios",
        "The debt-to-equity ratio equals",
        [
            "Total liabilities divided by total shareholders' equity",
            "Total assets divided by total equity",
            "Current liabilities divided by current assets",
            "Long-term debt divided by total assets",
        ],
        "Total liabilities divided by total shareholders' equity",
        "Medium",
        "Debt-to-equity compares creditor financing to owner financing.",
    ),
    q(
        "Financial Ratios",
        "Basic earnings per share (EPS) is computed as",
        [
            "(Net income - preferred dividends) / weighted-average common shares",
            "Net income / ending common shares",
            "Net sales / weighted-average shares",
            "Net income / total assets",
        ],
        "(Net income - preferred dividends) / weighted-average common shares",
        "Medium",
        "EPS allocates profit available to common shareholders over the weighted-average shares outstanding.",
    ),
    q(
        "Financial Ratios",
        "The price-earnings (P/E) ratio equals",
        [
            "Market price per share divided by earnings per share",
            "Earnings per share divided by dividends per share",
            "Net income divided by market price per share",
            "Market capitalization divided by total assets",
        ],
        "Market price per share divided by earnings per share",
        "Medium",
        "The P/E ratio shows how many dollars investors are willing to pay per dollar of earnings.",
    ),
    q(
        "Financial Ratios",
        "Dividend payout ratio is calculated as",
        [
            "Cash dividends divided by net income",
            "Net income divided by cash dividends",
            "Dividends divided by total assets",
            "Dividends divided by operating cash flow",
        ],
        "Cash dividends divided by net income",
        "Medium",
        "The payout ratio reveals what percentage of earnings are returned to shareholders as dividends.",
    ),
    q(
        "Financial Ratios",
        "Free cash flow (FCF) is most commonly defined as",
        [
            "Operating cash flow minus capital expenditures",
            "Net income minus dividends",
            "Operating income minus taxes",
            "Cash and cash equivalents minus current liabilities",
        ],
        "Operating cash flow minus capital expenditures",
        "Medium",
        "Free cash flow represents cash generated after funding necessary investments in long-term assets.",
    ),
    q(
        "Financial Ratios",
        "The cash conversion cycle equals",
        [
            "Days inventory outstanding + days sales outstanding − days payable outstanding",
            "Inventory turnover + receivables turnover + payables turnover",
            "Days sales outstanding × days inventory outstanding",
            "Operating cycle − working capital",
        ],
        "Days inventory outstanding + days sales outstanding − days payable outstanding",
        "Hard",
        "The cash conversion cycle measures the net time from paying suppliers to collecting from customers.",
    ),
    q(
        "Financial Ratios",
        "Operating cash flow ratio is computed as",
        [
            "Operating cash flow divided by current liabilities",
            "Operating cash flow divided by total debt",
            "Net income divided by operating cash flow",
            "Operating cash flow divided by net sales",
        ],
        "Operating cash flow divided by current liabilities",
        "Medium",
        "This ratio assesses whether operating cash generation can cover current obligations.",
    ),
    q(
        "Financial Ratios",
        "Which formula calculates accounts receivable turnover?",
        [
            "Net credit sales divided by average accounts receivable",
            "Average accounts receivable divided by net sales",
            "Accounts receivable divided by total assets",
            "Net sales divided by ending accounts receivable",
        ],
        "Net credit sales divided by average accounts receivable",
        "Medium",
        "Receivables turnover shows how many times the company collects its average receivables each period.",
    ),
]

# Cost & Managerial Accounting (15)
questions += [
    q(
        "Cost & Managerial Accounting",
        "Contribution margin equals",
        [
            "Sales revenue minus variable costs",
            "Sales revenue minus fixed costs",
            "Sales revenue minus total costs",
            "Variable costs minus fixed costs",
        ],
        "Sales revenue minus variable costs",
        "Easy",
        "Contribution margin represents the amount available to cover fixed costs and profit after variable costs are deducted.",
    ),
    q(
        "Cost & Managerial Accounting",
        "The break-even point in units is calculated by",
        [
            "Fixed costs divided by contribution margin per unit",
            "Fixed costs divided by selling price",
            "Contribution margin per unit divided by fixed costs",
            "Variable cost per unit divided by fixed costs",
        ],
        "Fixed costs divided by contribution margin per unit",
        "Medium",
        "At break-even, total contribution margin equals total fixed costs, so units = fixed costs / CM per unit.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which cost is included in prime cost?",
        ["Direct labor", "Factory utilities", "Office rent", "Sales commissions"],
        "Direct labor",
        "Easy",
        "Prime costs consist of direct materials and direct labor.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Conversion cost equals",
        [
            "Direct labor plus manufacturing overhead",
            "Direct materials plus direct labor",
            "Direct materials plus manufacturing overhead",
            "Variable cost plus fixed cost",
        ],
        "Direct labor plus manufacturing overhead",
        "Easy",
        "Conversion costs are the costs to convert materials into finished goods, namely direct labor and overhead.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which costing system accumulates costs by individual job or batch?",
        ["Job order costing", "Process costing", "Activity-based costing", "Variable costing"],
        "Job order costing",
        "Medium",
        "Job order systems track materials, labor, and overhead for specific customer jobs or batches.",
    ),
    q(
        "Cost & Managerial Accounting",
        "In process costing, 'equivalent units' represent",
        [
            "Partially completed units expressed as a number of whole units",
            "Actual units sold during the period",
            "The number of defective units",
            "Units budgeted for the next period",
        ],
        "Partially completed units expressed as a number of whole units",
        "Medium",
        "Equivalent units smooth partially completed inventory into whole units for cost assignment.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which variance compares actual fixed overhead spending to the budgeted amount?",
        [
            "Fixed overhead spending variance",
            "Fixed overhead volume variance",
            "Variable overhead efficiency variance",
            "Direct labor rate variance",
        ],
        "Fixed overhead spending variance",
        "Hard",
        "The spending variance isolates the difference between actual and budgeted fixed overhead costs.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which budgeting approach requires managers to justify all expenses from a zero base?",
        ["Zero-based budgeting", "Flexible budgeting", "Rolling budgeting", "Static budgeting"],
        "Zero-based budgeting",
        "Medium",
        "Zero-based budgets build each line item from scratch rather than adjusting last year's numbers.",
    ),
    q(
        "Cost & Managerial Accounting",
        "A relevant cost is best described as",
        [
            "A future cost that differs between alternatives",
            "Any sunk cost already incurred",
            "A cost that never varies",
            "A cost reported on the income statement",
        ],
        "A future cost that differs between alternatives",
        "Medium",
        "Only future, differential costs influence decision making; sunk costs are irrelevant.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which cost remains constant per unit but varies in total with activity level?",
        ["Variable cost", "Fixed cost", "Mixed cost", "Step cost"],
        "Variable cost",
        "Easy",
        "Variable costs change in total as volume changes but the per-unit amount stays constant.",
    ),
    q(
        "Cost & Managerial Accounting",
        "The margin of safety indicates",
        [
            "How much sales can drop before the company reaches break-even",
            "The percentage markup on cost",
            "The contribution margin per unit",
            "Budgeted sales for next year",
        ],
        "How much sales can drop before the company reaches break-even",
        "Medium",
        "Margin of safety compares actual or budgeted sales to break-even sales to show the risk cushion.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Finished goods inventory consists of",
        [
            "Completed products awaiting sale",
            "Raw materials awaiting production",
            "Partially completed units",
            "Merchandise held on consignment",
        ],
        "Completed products awaiting sale",
        "Easy",
        "Finished goods are ready for sale, unlike raw materials or work in process.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Which cost is treated as a period cost in manufacturing companies?",
        ["Sales salaries", "Direct materials", "Direct labor", "Factory depreciation"],
        "Sales salaries",
        "Medium",
        "Selling and administrative costs are expensed in the period incurred rather than inventoried.",
    ),
    q(
        "Cost & Managerial Accounting",
        "The contribution margin ratio equals",
        [
            "Contribution margin divided by sales",
            "Contribution margin divided by fixed costs",
            "Sales divided by contribution margin",
            "Sales divided by fixed costs",
        ],
        "Contribution margin divided by sales",
        "Easy",
        "The CM ratio shows the percentage of each sales dollar available for fixed costs and profit.",
    ),
    q(
        "Cost & Managerial Accounting",
        "Why is a predetermined overhead rate used?",
        [
            "To allocate manufacturing overhead to cost objects during the period",
            "To record actual overhead costs as they occur",
            "To estimate direct labor requirements",
            "To determine sales commissions",
        ],
        "To allocate manufacturing overhead to cost objects during the period",
        "Medium",
        "Predetermined rates apply overhead to jobs or processes before actual costs are fully known.",
    ),
]

# Internal Control & Ethics (15)
questions += [
    q(
        "Internal Control & Ethics",
        "What is the primary objective of segregating duties?",
        [
            "To reduce the risk that one person can both perpetrate and conceal errors or fraud",
            "To speed up transaction processing",
            "To comply with tax laws",
            "To eliminate the need for supervision",
        ],
        "To reduce the risk that one person can both perpetrate and conceal errors or fraud",
        "Easy",
        "Segregation of authorization, custody, and recording functions prevents a single employee from controlling all steps.",
    ),
    q(
        "Internal Control & Ethics",
        "The purpose of a bank reconciliation is to",
        [
            "Match the cash balance per books with the balance per bank statement",
            "Compute interest revenue",
            "Prepare payroll",
            "Calculate accounts receivable turnover",
        ],
        "Match the cash balance per books with the balance per bank statement",
        "Easy",
        "Bank reconciliations identify timing differences and errors between the company's records and the bank.",
    ),
    q(
        "Internal Control & Ethics",
        "Which law created the Public Company Accounting Oversight Board (PCAOB)?",
        [
            "Sarbanes-Oxley Act of 2002",
            "Dodd-Frank Act",
            "Securities Exchange Act of 1934",
            "Foreign Corrupt Practices Act",
        ],
        "Sarbanes-Oxley Act of 2002",
        "Medium",
        "SOX established the PCAOB to oversee audits of public companies.",
    ),
    q(
        "Internal Control & Ethics",
        "Which component is part of the COSO internal control framework?",
        ["Control environment", "Market capitalization", "Share price", "Tax expense"],
        "Control environment",
        "Medium",
        "COSO identifies control environment, risk assessment, control activities, information & communication, and monitoring.",
    ),
    q(
        "Internal Control & Ethics",
        "Which element is NOT part of the fraud triangle?",
        ["Lack of training", "Pressure", "Opportunity", "Rationalization"],
        "Lack of training",
        "Medium",
        "The fraud triangle consists of pressure, opportunity, and rationalization.",
    ),
    q(
        "Internal Control & Ethics",
        "Why are prenumbered documents used?",
        [
            "To ensure all transactions are recorded and none are duplicated",
            "To speed up mailing",
            "To satisfy tax authorities",
            "To reduce storage costs",
        ],
        "To ensure all transactions are recorded and none are duplicated",
        "Easy",
        "Prenumbering provides a completeness control so missing or duplicate documents can be detected.",
    ),
    q(
        "Internal Control & Ethics",
        "Restricting access to inventory storerooms primarily addresses which risk?",
        [
            "Theft or misuse of assets",
            "Currency exchange fluctuations",
            "Interest rate risk",
            "Foreign tax exposure",
        ],
        "Theft or misuse of assets",
        "Easy",
        "Limiting physical access protects assets from theft and unauthorized use.",
    ),
    q(
        "Internal Control & Ethics",
        "What is the role of an internal audit function?",
        [
            "Evaluate the effectiveness of internal controls and risk management",
            "Approve all journal entries",
            "Set product prices",
            "File tax returns",
        ],
        "Evaluate the effectiveness of internal controls and risk management",
        "Medium",
        "Internal auditors provide independent assurance that controls operate as intended.",
    ),
    q(
        "Internal Control & Ethics",
        "Matching supplier invoices to purchase orders and receiving reports before payment is an example of",
        [
            "Three-way match control",
            "Bank reconciliation",
            "Physical inventory count",
            "Variance analysis",
        ],
        "Three-way match control",
        "Medium",
        "Three-way matching ensures goods were ordered and received before cash is disbursed, preventing duplicate or fraudulent payments.",
    ),
    q(
        "Internal Control & Ethics",
        "Requiring employees in sensitive roles to take vacations helps",
        [
            "Detect irregularities that may be hidden by continuous control",
            "Reduce payroll expense",
            "Improve customer service",
            "Decrease tax liability",
        ],
        "Detect irregularities that may be hidden by continuous control",
        "Medium",
        "Mandatory vacations allow another person to perform the duties and increases the chance of uncovering fraud.",
    ),
    q(
        "Internal Control & Ethics",
        "Which control is demonstrated by requiring unique passwords for accounting system access?",
        ["Access control", "Physical control", "Independent verification", "Budgetary control"],
        "Access control",
        "Easy",
        "Passwords restrict system access to authorized users, preventing unauthorized data changes.",
    ),
    q(
        "Internal Control & Ethics",
        "The ethical principle of objectivity requires accountants to",
        [
            "Avoid conflicts of interest and bias when presenting information",
            "Maximize company profit at all costs",
            "Follow management orders regardless of legality",
            "Focus only on tax savings",
        ],
        "Avoid conflicts of interest and bias when presenting information",
        "Medium",
        "Objectivity demands impartial judgment and disclosure of any conflicts that could impair fairness.",
    ),
    q(
        "Internal Control & Ethics",
        "Requiring documented approval before recording significant transactions provides",
        ["Authorization control", "Physical safeguard", "Budgetary control", "Market control"],
        "Authorization control",
        "Easy",
        "Authorization ensures transactions are reviewed and approved by responsible personnel before entry.",
    ),
    q(
        "Internal Control & Ethics",
        "When an employee suspects fraud, the preferred first step is to",
        [
            "Report the concern through the organization's designated hotline or supervisor",
            "Confront the suspected individual directly",
            "Alert the media",
            "Ignore it until year-end",
        ],
        "Report the concern through the organization's designated hotline or supervisor",
        "Medium",
        "Most ethics programs require using established reporting channels so investigations can proceed properly.",
    ),
    q(
        "Internal Control & Ethics",
        "Which control objective is addressed by independent bank confirmations of cash balances?",
        [
            "Verification of existence and accuracy",
            "Optimization of profitability",
            "Compliance with environmental laws",
            "Computation of bonus pools",
        ],
        "Verification of existence and accuracy",
        "Medium",
        "Direct confirmation from banks provides third-party assurance over recorded cash balances.",
    ),
]

EXPECTED_COUNT = 110
assert len(questions) == EXPECTED_COUNT, len(questions)
for idx, item in enumerate(questions, start=1):
    if not str(item["explanation"]).strip():
        raise ValueError(f"Question {idx} is missing an explanation.")

df = pd.DataFrame(questions)
df["options"] = df["options"].apply(json.dumps)
df["correct_answers"] = df["correct_answers"].apply(json.dumps)
df["allow_multiple"] = df["allow_multiple"].astype(bool)
df.insert(0, "id", range(1, len(df) + 1))
df.to_csv("data/questions.csv", index=False)
